mingchen/docker-android-build-box

Dockerfile
README.md

Fix npm Issue:
npm clean cache needs the force argument to work.
Use sdkmanager:
This approach requires Android SDK tools 26.
We install latest Android SDK tools, latest platforms, and latest build
tools.
Add Emulator - it could be useful for testing.
Users can use this image as a base and then install their own android
system image on top of it.
Use Ubuntu 17.10 Image - this brings latest stable versions of packages
and could fix some bugs with them.
Silence Commands - the logs are huge so we redirect stdout to /dev/null.
Warnings and errors appear on stderr so we do not need usually care for
stdout.
Add Latest x86_64 System Image
Since we included an emulator, we can include one system image too. The
images are quite large so we install only the latest SDK. Users can use
the docker …

Fix npm Issue, Use sdkmanager, Add Emulator, Install Cordova and Ionic

---

Dockerfile

Environment variables cannot be referenced in the same line they are created. They need to be moved to a later ENV statement.
Also, using comments within a multi-line statement causes docker warnings, so these are now separate statements.

Fix environment variable concatenation

---

Dockerfile
README.md

Fix issue #18
* Remove pre-installed x86_64 emulator system image, as it cannot run in the Docker image.
* In Readme.md, explain how to create and launch an ARM emulator in the Docker image. Mention that x86_64 emulators do not currently work.

Issue #18 fix patch: Remove pre-installed x86_64 emulator. Explain how to create and launch an ARM emulator

---

Dockerfile

This PR addresses the problems experienced today with apt-get update and other apt operations failing because (presumably) ubuntu:17.10 apt repositories going away.
Minor changes were required to get the build working when migrating to ubuntu:18.04 - the addition of installing gpg-agent, and replacing `python-software-properties` with `software-properties-common` when installing packages via apt.
The build completes successfully with these changes. My tests so far have been limited to my own use though.

Updates to use ubuntu:18.04 as base

---

Dockerfile

NDK r19 has a bug as reported [here](https://github.com/android-ndk/ndk/issues/849).
This pull request simply update NDK version to r20 on 1.10.0.
I have confirmed that this change resolves the issue with building android library with gomobile.

Use NDK r20

---

Dockerfile

fixes #35 (adds the "file" command required by ndk-build).
On top, we propose less & vim-tiny for further investigations when needed.
It adds only 2Mb to the existing 5Gb image, hope that's ok.

fixing #35 plus less/vim-tiny

---

Dockerfile
Gemfile

* Install yarn package manager
* Use bundle install to install fastlane and dependencies, Add Gemfile (#1)
* Add Gemfile, update Docker to install fastlane & dependencies via bundle install
* Make /.fastlane folder
* Update Dockerfile to add ENV BUNDLE_GEMFILE
After testing Android build using fastlane, the default fastlane installed on the image used to fail. The `/.fastlane` folder wasn't writable, and fastlane kept missing dependencies. So I installed fastlane using bundler to take care of the dependencies. I also added the yarn package manager which quite a few teams use instead of npm. Feedback welcome.

Update Dockerfile to install Yarn, fastlane using bundler

---

Dockerfile
README.md

Fix for Issue #45 
Remove old Build Tools (versions 24-17), and old Android Platform versions (versions 24-16), and old Google APIs (versions 24-16)
* "platforms;android-24"
* "platforms;android-23"
* "platforms;android-22"
* "platforms;android-21"
* "platforms;android-20"
* "platforms;android-19"
* "platforms;android-18"
* "platforms;android-17"
* "platforms;android-16"
* "build-tools;24.0.3"
* "build-tools;24.0.2"
* "build-tools;24.0.1"
* "build-tools;24.0.0"
* "build-tools;23.0.3"
* "build-tools;23.0.2"
* "build-tools;23.0.1"
* "build-tools;22.0.1"
* "build-tools;21.1.2"
* "build-tools;20.0.0"
* "build-tools;19.1.0"
* "build-tools;18.1.1"
* "build-tools;17.0.0"
* "add-ons;addon-google_apis-google-24"
* "add-ons;addon-google_apis-google-23"
* "add-ons;addon-google_apis-google-22"
* …

Patch for #45: Remove old Build Tools and old Android Platform versions

---

Dockerfile
README.md

The following components are installed on the Docker images of `android-build-box`:
* extras-android-m2repository
* extras-google-m2repository
* extras-google-google_play_services
* extras-m2repository-constraint-layout-1.0.2
* extras-m2repository-constraint-layout-1.0.1
They will download about 550 MB of library dependencies to the `$ANDROID_HOME/extras` folder, which will act like a local Maven repository ("m2repository"). It contains things like Google Play Services, Android Support libraries, RecyclerView, Constraint Layout, etc.
The "extras" folder is deprecated, because gradle will now download these libraries on-demand, from https://maven.google.com -- even for the very old versions. This has been available since at least July 2017. You can browse https://maven.google.com and use …

Patch for Issue #49 - Remove all the "extras" items of local libraries, in the Android SDK

---

Dockerfile

This feature may be exactly what you *don't* want, but suggesting that the permissions for the Android SDK tools be updatable within the Docker container by Jenkins.
This pattern would fix the issue where Jenkins (as non-root user) does not have permission to update Android SDK components and built tool versions when they get updated from within an Android project's build.gradle file.
Please feel free to modify this however you like too.  Thanks

Make the Android SDK updatable?

---

Dockerfile
README.md

* Remove old build tools of `"build-tools;25.0.3"`, `"build-tools;25.0.2"`, `"build-tools;25.0.1"` `"build-tools;25.0.0"`. These were used at approximately September 2017, so no modern Android project will be using them now, 4 years later. The corresponding `"platforms;android-25"` is also removed.
* Kotlin 1.5, Gradle 7.2 and SDKMan are also removed, because all Android apps are setup to use their own specific versions of Kotlin and Gradle, so the system versions of Kotlin and gradle are never used. Android apps will use gradlew to download their own version of gradle, as defined in the `gradle-wrapper.properties` file of their project. Similarly, the project's `build.gradle` file will specify a unique version of Kotlin to download, using this: `implementation …

Fixes for Issue #75: Tidy up: Delete old build tools, remove unnecessary things, update documentation

---

Dockerfile

Newer versions of Git cause a problem when running `flutter pub get` inside `android-build-box` because the `/opt/flutter` directory is not considered safe to be cloned to.
See https://stackoverflow.com/questions/71849415/i-cannot-add-the-parent-directory-to-safe-directory-in-git

Fix issue with safe-directory in newer Git

---

.github/workflows/docker-image.yml
Dockerfile
test_projects/SampleProject/.java-version

I think this should resolve #108. I tested all the tests which the docker build test runs locally and they all passed.
I added jenv's `.java-version` to the SampleProject. This sets the local java version to use in that folder.
I tried to use `.bashrc` and `/etc/profile` but neither of them would work for any command of `docker run --rm $IMAGE_NAME:$TAG bash -c 'jenv versions'`. There is also setting `$BASH_ENV` and when I set that to `/root/.bash_profile` bash would just hang and not get anywhere. So I opted to resolve it by just permanently adding jenv to the PATH via the Dockerfile. The downside is when one sources `.bash_profule` there is one duplication.
I've also done some additional improvements to the docker build test.
I am reasonably confident that this should fix get the build …

Improve build test

---

Dockerfile

I'm not sure what your version scheme is like. But here are some updates to the installed software.
~~There's also a CI change which should, if I got everything right, reduce the build time in half (only builds image once).~~
Other changes which I think should occur:
- drop SDK 27
- drop SDK 28
- drop SDK 29
- Add newer build tools
- Update command line tools
- Set up "smart" versioning (will open an issue for this to explain / discuss)
- - use jEnv specific version
- - use Ndk specific version

Proposed next release

---

.github/workflows/docker-image.yml

Change to build the image using docker action. Subsequently reducing build time
~50%, as the image will only need to be built once. Currently image is
built twice.
The default driver uses double the disk space, see
https://github.com/docker/build-push-action/issues/321 (in brief, the image is built in the
build-push-action local cache, `tar`ed, and then transfered to the local docker).
This is a problem as this image is so large. Using the `docker` driver
will workaround this.
Removes the Android SDK and the Hosted tool cache from the runner.
The hostedtoolcache has the following unused software:
- PyPy
- go
- CodeQL
- Java_Temurin-Hotspot_jdk
- node
- Ruby
- Python
This frees up ~23G from the disk space.

CI: Streamline docker build

---

.github/workflows/docker-image.yml

This should fix the CI dockerhub description update. #124 used the wrong key.

CI: Fix dockerhub-description password

---

README.md

Update the README to mention that the Dockerhub listing has listed all of the *latest* tagged software as a result of #160.

DOCS: Update Readme - #160

---

.github/workflows/docker-image.yml
Dockerfile

Upgrade to use hopefully use a later version of ruby by default allowing for latest bundler to be used. Using 20.04 causes bundler to fail to install due to Ruby 2.7 being used instead of the required 3.0.

Upgrade to Ubuntu 22.04 LTS

---

.github/workflows/docker-image.yml

When tags where build & pushed to Docker Hub, the build arguments added in as a result of https://github.com/mingchen/docker-android-build-box/issues/116 where not included. This fix should make the tagged version use the correct build arguments. By doing so the correct docker image should be built and pushed to Docker Hub.
Tags which are affected by this on Docker Hub which should be re-pushed are `1.27.0` and `1.26.0`.
This should resolve #178 .

CI: Fixup build and push #178 & minor improvements

---

Dockerfile

This pull request adds missing [Ninja C++ build system](https://github.com/ninja-build/ninja) package that is used as the [experimental C/C++ build system](https://developer.android.com/build/cxx-ninja) for Android builds.
This package is distributed for Ubuntu as `ninja-build` package.
Without this package, some builds might fail by not being able to find this binary:
```
> Task :app:configureCMakeRelWithDebInfo[armeabi-v7a] FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:configureCMakeRelWithDebInfo[armeabi-v7a]'.
> [CXX1416] Could not find Ninja on PATH or in SDK CMake bin folders.
```

Add missing Ninja package

---

Dockerfile
README.md
tagged_sdk_packages_list.txt

- Add Android Platform 35
- Upgrade Flutter 3.19.2 -> 3.24.5
- Upgrade bundletool 1.15.6 -> 1.18.1
- Upgrade 20.x (also LTS) -> 22.x
- Upgrade to latest Android CLT 13114758
- Upgrade Android NDK r26c -> r28c

Updates / Changes for proposed Next Release
